### ISSUE TITLE
Scrollbar not appearing when container/widgets gets bigger after first build

### ISSUE THREAD

**Issue by aravinds0903** [Mehrankhan-METRA-RGB/cross_scroll#5]
### Issue Description
When using the Cross Scroll package, I've noticed that the scroll doesn't appear when the widget gets bigger after build.

**Steps to Reproduce**

1. Create a Cross Scroll widget with multiple lists or grids
2. Add content to the lists or grids that exceed the available space after the first build
3. Observe that the scroll does not appear automatically when the widget gets bigger

**Expected Behavior**
I would expect the **scrollBar** to appear automatically when the widget size exceeds the available space.

**Actual Behavior**
The **scrollBar** is not appearing when the widget gets bigger, making it difficult to scroll through the content.

![crossScroll](https://user-images.githubusercontent.com/108114959/220839862-d29d56d2-0712-4b9e-ba3c-d6171809211d.gif)

Test code:
```sh
import 'package:cross_scroll/cross_scroll.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyWidget());
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    bool _isExpanded = false;
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Expanded Container'),
        ),
        body: LayoutBuilder(builder: (context, constraints) {
          return CrossScroll(
            child: StatefulBuilder(builder: (context, setState) {
              return Column(
                children: [
                  GestureDetector(
                    onTap: () {
                      setState(() {
                        _isExpanded = !_isExpanded;
                      });
                    },
                    child: Container(
                      width: constraints.maxWidth,
                      height: _isExpanded ? constraints.maxHeight * 1.2 : constraints.maxHeight * 0.5,
                      color: Colors.blue,
                      child: Center(
                        child: Text(
                          _isExpanded ? 'you will not see scrollBar --->' : 'Tap to Expand',
                          style: TextStyle(
                            fontSize: 30,
                            color: Colors.black,
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              );
            }),
          );
        }),
      ),
    );
  }
}

```

Environment
Cross Scroll package version: cross_scroll: ^0.0.75
Flutter version: Flutter (Channel stable, 3.7.3, on Ubuntu 22.04.1 LTS 5.19.0-32-generic, locale en_US.UTF-8)
Test Device: Web/Linux

**Test Cases that it should also  work:**
- [x] widget is first bigger than the screen then gets smaller (scrollBar should update to the new size)
- [x] widget is first bigger than the screen then gets even bigger  (scrollBar should update to the new size)

**Comment by Mehrankhan-METRA-RGB** [comment]
@aravind-aimedlabs  The scroll view parent and child both have static height and width.

**Comment by toplinuxsir** [comment]
@Mehrankhan-METRA-RGB  I meet the same problem How to resolve it ? Thanks!

**Comment by Mehrankhan-METRA-RGB** [comment]
I appreciate your work. i will work on it soon. thanks again

________________________________
From: Aravind Selvaraj ***@***.***>
Sent: 23 February 2023 12:09
To: Mehrankhan-METRA-RGB/cross_scroll ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Mehrankhan-METRA-RGB/cross_scroll] Scrollbar not appearing when container/widgets gets bigger after first build (Issue #5)


Issue Description

When using the Cross Scroll package, I've noticed that the scroll doesn't appear when the widget gets bigger after build.

Expected Behavior
I would expect the scroll to appear automatically when the widget size exceeds the available space.

Actual Behavior
The scroll is not appearing when the widget gets bigger, making it difficult to scroll through the content.

[crossScroll]<https://user-images.githubusercontent.com/108114959/220839862-d29d56d2-0712-4b9e-ba3c-d6171809211d.gif>

Steps to Reproduce
Create a Cross Scroll widget with multiple lists or grids
Add content to the lists or grids that exceed the available space after the first build
Observe that the scroll does not appear automatically when the widget gets bigger

Test code:

import 'package:cross_scroll/cross_scroll.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyWidget());
}

class MyWidget extends StatelessWidget {
  const MyWidget({super.key});

  @override
  Widget build(BuildContext context) {
    bool _isExpanded = false;
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Expanded Container'),
        ),
        body: LayoutBuilder(builder: (context, constraints) {
          return CrossScroll(
            child: StatefulBuilder(builder: (context, setState) {
              return Column(
                children: [
                  GestureDetector(
                    onTap: () {
                      setState(() {
                        _isExpanded = !_isExpanded;
                      });
                    },
                    child: Container(
                      width: constraints.maxWidth,
                      height: _isExpanded ? constraints.maxHeight * 1.2 : constraints.maxHeight * 0.5,
                      color: Colors.blue,
                      child: Center(
                        child: Text(
                          _isExpanded ? 'you will not see scrollBar --->' : 'Tap to Expand',
                          style: TextStyle(
                            fontSize: 30,
                            color: Colors.black,
                          ),
                        ),
                      ),
                    ),
                  ),
                ],
              );
            }),
          );
        }),
      ),
    );
  }
}


Environment
Cross Scroll package version: cross_scroll: ^0.0.75
Flutter version: Flutter (Channel stable, 3.7.3, on Ubuntu 22.04.1 LTS 5.19.0-32-generic, locale en_US.UTF-8)
Test Device: Web/Linux

**Comment by Mehrankhan-METRA-RGB** [comment]
@aravind-aimedlabs  This issue has been solved as requested check our new package version.

Thanks for filing an issue please feel free to place points here.
